// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biograph: dynamic(() => import("./Biograph")),
  hero: dynamic(() => import("./Hero")),
};
